# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: Req.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto


@dataclass
class UseTicketReq(betterproto.Message):
    codaid: int = betterproto.uint32_field(1)
    is_new: bool = betterproto.bool_field(2)
    auto_use_ticket: bool = betterproto.bool_field(3)
    product_id: str = betterproto.string_field(4)


@dataclass
class AvideoReq(betterproto.Message):
    codaid: int = betterproto.uint32_field(1)


@dataclass
class Timestamp(betterproto.Message):
    seconds: int = betterproto.uint32_field(1)
    nanos: int = betterproto.uint32_field(2)


@dataclass
class SearchAvideoReq(betterproto.Message):
    page: int = betterproto.uint32_field(1)
    limit: int = betterproto.uint32_field(2)
    actress_ids_list: List[int] = betterproto.uint32_field(3)
    is_av_plus: bool = betterproto.bool_field(4)
    stream_publish_at_start: "Timestamp" = betterproto.message_field(5)
    stream_publish_at_end: "Timestamp" = betterproto.message_field(6)
    sort_rule: int = betterproto.uint32_field(7)
    only_old_avideo: bool = betterproto.bool_field(8)
    launched_at_start: "Timestamp" = betterproto.message_field(9)
    launched_at_end: "Timestamp" = betterproto.message_field(10)
    hide_compilation: bool = betterproto.bool_field(11)
    keyword_ids_list: List[int] = betterproto.uint32_field(12)
    popular_at_end: "Timestamp" = betterproto.message_field(13)
    publisher_list: List[str] = betterproto.string_field(14)
    series: str = betterproto.string_field(15)


@dataclass
class IdsReq(betterproto.Message):
    ids: List[int] = betterproto.uint32_field(1)


@dataclass
class AvideoListReq(betterproto.Message):
    page: int = betterproto.uint32_field(1)
    limit: int = betterproto.uint32_field(2)
    no: str = betterproto.string_field(3)
    actress_id: int = betterproto.uint32_field(4)
    keyword_id: int = betterproto.uint32_field(5)
    is_av_plus: bool = betterproto.bool_field(6)
    sort_by_hardcore: bool = betterproto.bool_field(7)


@dataclass
class SearchPlaylistReq(betterproto.Message):
    page: int = betterproto.uint32_field(1)
    limit: int = betterproto.uint32_field(2)
    keyword: str = betterproto.string_field(3)
    create_at_start: "Timestamp" = betterproto.message_field(4)
    create_at_end: "Timestamp" = betterproto.message_field(5)
    channel_ids_list: List[int] = betterproto.uint32_field(6)
    without_favorite_count: bool = betterproto.bool_field(7)


@dataclass
class AvideoScheduleReq(betterproto.Message):
    start_at: "Timestamp" = betterproto.message_field(1)
    end_at: "Timestamp" = betterproto.message_field(2)
    type: int = betterproto.uint32_field(3)


@dataclass
class ActressListReq(betterproto.Message):
    page: int = betterproto.uint32_field(1)
    limit: int = betterproto.uint32_field(2)
    name: str = betterproto.string_field(3)
    actress_id: int = betterproto.uint32_field(4)
