# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: Res.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto


@dataclass
class ChechMemberRes(betterproto.Message):
    """
    '/speedjav.client.ClientService/CheckMember' -H 'authorization:
    `access_token`' --data-raw 'AAAAAAA='
    """

    member_status: bool = betterproto.bool_field(1)
    code: int = betterproto.uint32_field(2)
    invite_code: str = betterproto.string_field(3)
    invite_count: int = betterproto.uint32_field(4)


@dataclass
class Language(betterproto.Message):
    jp: str = betterproto.string_field(1)
    tw: str = betterproto.string_field(2)
    en: str = betterproto.string_field(3)


@dataclass
class Timestamp(betterproto.Message):
    seconds: int = betterproto.uint32_field(1)
    nanos: int = betterproto.uint32_field(2)


@dataclass
class Keyword(betterproto.Message):
    id: int = betterproto.uint32_field(1)
    name: "Language" = betterproto.message_field(2)


@dataclass
class Actress(betterproto.Message):
    id: int = betterproto.uint32_field(1)
    name: "Language" = betterproto.message_field(2)
    has_avatar: bool = betterproto.bool_field(3)
    avideo_count: int = betterproto.uint32_field(4)


@dataclass
class Publisher(betterproto.Message):
    id: int = betterproto.uint32_field(1)
    name: str = betterproto.string_field(2)
    display_name: str = betterproto.string_field(3)
    icon_url: str = betterproto.string_field(4)
    avideo_count: int = betterproto.uint32_field(5)
    favorite_count: int = betterproto.uint32_field(6)
    actress_count: int = betterproto.uint32_field(7)


@dataclass
class Series(betterproto.Message):
    tw: str = betterproto.string_field(1)
    jp: str = betterproto.string_field(2)


@dataclass
class AvideoDetailRes(betterproto.Message):
    """
    '/speedjav.client.ClientService/AvideoDetail'   -H 'authorization:
    `access_token`' --data-raw `hash2Id`
    """

    codaid: int = betterproto.uint32_field(1)
    no: str = betterproto.string_field(2)
    product_id: str = betterproto.string_field(3)
    title: "Language" = betterproto.message_field(4)
    start_at: "Timestamp" = betterproto.message_field(5)
    keyword_list: List["Keyword"] = betterproto.message_field(6)
    actress_list: List["Actress"] = betterproto.message_field(7)
    duration: int = betterproto.uint32_field(8)
    is_av_plus: bool = betterproto.bool_field(9)
    is_hd: bool = betterproto.bool_field(10)
    code: int = betterproto.uint32_field(11)
    preview_num: int = betterproto.uint32_field(12)
    viewable_index: int = betterproto.uint32_field(13)
    stills_num: int = betterproto.uint32_field(14)
    resolution: str = betterproto.string_field(15)
    has_subtitle: bool = betterproto.bool_field(16)
    has_bought_subtitle: bool = betterproto.bool_field(17)
    publisher: "Publisher" = betterproto.message_field(18)
    series: "Series" = betterproto.message_field(19)


@dataclass
class StatusRes(betterproto.Message):
    """
    '/speedjav.client.ClientService/GenTs'  -H 'authorization: `access_token`'
    --data-raw `hash2Id`
    """

    status: bool = betterproto.bool_field(1)
    code: int = betterproto.uint32_field(2)


@dataclass
class AvideoSubtitleRes(betterproto.Message):
    """
    '/speedjav.client.ClientService/AvideoSubtitle'  -H 'authorization:
    `access_token`' --data-raw `hash2Id`
    """

    subtitle: str = betterproto.string_field(1)


@dataclass
class AtokenRes(betterproto.Message):
    """AccessToken and UseTicket"""

    token1: str = betterproto.string_field(1)
    token2: str = betterproto.string_field(2)


@dataclass
class AvideoBriefLite(betterproto.Message):
    codaid: int = betterproto.uint32_field(1)
    no: str = betterproto.string_field(2)
    product_id: str = betterproto.string_field(3)
    title: "Language" = betterproto.message_field(4)
    start_at: "Timestamp" = betterproto.message_field(5)
    actress_ids_list: List[int] = betterproto.uint32_field(6)
    is_av_plus: bool = betterproto.bool_field(7)
    is_hd: bool = betterproto.bool_field(8)
    launched_at: "Timestamp" = betterproto.message_field(9)
    has_subtitle: bool = betterproto.bool_field(10)


@dataclass
class SearchAvideoRes(betterproto.Message):
    """
    "/speedjav.client.ClientService/SearchAvideo" -H 'authorization:
    `access_token`' --data-raw SearchAvideoReq
    """

    avideo_list: List["AvideoBriefLite"] = betterproto.message_field(1)
    total: int = betterproto.uint32_field(2)


@dataclass
class ActressListRes(betterproto.Message):
    """
    "/speedjav.client.ClientService/ActressListByIds" -H 'authorization:
    `access_token`' --data-raw IdsReq
    """

    actress_list: List["Actress"] = betterproto.message_field(1)
    code: int = betterproto.uint32_field(2)
    total: int = betterproto.uint32_field(3)


@dataclass
class Publishers(betterproto.Message):
    """
    "/speedjav.client.ClientService/PublisherListByIds" -H 'authorization:
    `access_token`' --data-raw IdsReq
    """

    publisher_list: List["Publisher"] = betterproto.message_field(1)


@dataclass
class AvideoListRes(betterproto.Message):
    """
    "/speedjav.client.ClientService/AvideoList" -H 'authorization:
    `access_token`' --data-raw AvideoListReq
    """

    avideo_list: List["AvideoBrief"] = betterproto.message_field(1)
    code: int = betterproto.uint32_field(2)
    total: int = betterproto.uint32_field(3)


@dataclass
class AvideoBrief(betterproto.Message):
    codaid: int = betterproto.uint32_field(1)
    no: str = betterproto.string_field(2)
    product_id: str = betterproto.string_field(3)
    title: "Language" = betterproto.message_field(4)
    start_at: "Timestamp" = betterproto.message_field(5)
    actress_list: List["Actress"] = betterproto.message_field(6)
    is_av_plus: bool = betterproto.bool_field(7)
    is_hd: bool = betterproto.bool_field(8)
    event_at: "Timestamp" = betterproto.message_field(9)
    is_off: bool = betterproto.bool_field(10)
    has_subtitle: bool = betterproto.bool_field(11)


@dataclass
class SearchPlaylistRes(betterproto.Message):
    playlists_list: List["Playlist"] = betterproto.message_field(1)
    total: int = betterproto.uint32_field(2)


@dataclass
class Playlist(betterproto.Message):
    id: str = betterproto.string_field(1)
    title: str = betterproto.string_field(2)
    cover_type: int = betterproto.uint32_field(3)
    cover_url_list: List[str] = betterproto.string_field(4)
    cover_codaid_list: List[int] = betterproto.uint32_field(5)
    channel_id: str = betterproto.string_field(6)
    channel_name: str = betterproto.string_field(7)
    channel_cover_url: str = betterproto.string_field(8)
    favorited_count: int = betterproto.uint32_field(9)
    avideo_count: int = betterproto.uint32_field(10)
    created_at: List["Timestamp"] = betterproto.message_field(11)
    codaid_list: List[int] = betterproto.uint32_field(12)
    description: str = betterproto.string_field(13)
    channel_owner_id: int = betterproto.uint32_field(14)
    generator_type: str = betterproto.string_field(15)
    channel_is_official: bool = betterproto.bool_field(16)
    status: int = betterproto.uint32_field(17)


@dataclass
class AvideoScheduleRes(betterproto.Message):
    data_map: List["AvideoScheduleDataMap"] = betterproto.message_field(1)


@dataclass
class AvideoSchedule(betterproto.Message):
    codaid_list: List[int] = betterproto.uint32_field(1)
    avplus_codaids_list: List[int] = betterproto.uint32_field(2)


@dataclass
class AvideoScheduleDataMap(betterproto.Message):
    key: str = betterproto.string_field(1)
    data_map: "AvideoSchedule" = betterproto.message_field(2)
